// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 23 Jun 2017 22:04:27 MDT.
// By https://git.io/cgogen. DO NOT EDIT.

#include "monitor.h"
#include "maincpu.h"
#include "mem.h"
#include "video.h"
#include "init.h"
#include "diskimage.h"
#include "debug.h"
#include "monitor/mon_breakpoint.h"
#include "c64/c64mem.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// monitor_toggle_func_t_cf2e566a is a proxy for callback monitor_toggle_func_t.
void monitor_toggle_func_t_cf2e566a(int value);

