// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 23 Jun 2017 22:04:27 MDT.
// By https://git.io/cgogen. DO NOT EDIT.

package vice

/*
#include "monitor.h"
#include "maincpu.h"
#include "mem.h"
#include "video.h"
#include "init.h"
#include "diskimage.h"
#include "debug.h"
#include "monitor/mon_breakpoint.h"
#include "c64/c64mem.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
// VideoFilterNone as defined in vice\video.h:33
VideoFilterNone = 0
// VideoFilterCrt as defined in vice\video.h:34
VideoFilterCrt = 1
// VideoFilterScale2x as defined in vice\video.h:35
VideoFilterScale2x = 2
// VideoRenderNull as defined in vice\video.h:40
VideoRenderNull = 0
// VideoRenderPal1x1 as defined in vice\video.h:42
VideoRenderPal1x1 = 1
// VideoRenderPal2x2 as defined in vice\video.h:43
VideoRenderPal2x2 = 2
// VideoRenderRgb1x1 as defined in vice\video.h:45
VideoRenderRgb1x1 = 3
// VideoRenderRgb1x2 as defined in vice\video.h:46
VideoRenderRgb1x2 = 4
// VideoRenderRgb2x2 as defined in vice\video.h:47
VideoRenderRgb2x2 = 5
// VideoRenderRgb2x4 as defined in vice\video.h:48
VideoRenderRgb2x4 = 6
// VideoRenderCrt1x1 as defined in vice\video.h:50
VideoRenderCrt1x1 = 7
// VideoRenderCrt1x2 as defined in vice\video.h:51
VideoRenderCrt1x2 = 8
// VideoRenderCrt2x2 as defined in vice\video.h:52
VideoRenderCrt2x2 = 9
// VideoRenderCrt2x4 as defined in vice\video.h:53
VideoRenderCrt2x4 = 10
// VideoMaxOutputWidth as defined in vice\video.h:136
VideoMaxOutputWidth = 2048
// DiskImageDeviceFs as defined in vice\diskimage.h:56
DiskImageDeviceFs = 0
// DiskImageDeviceReal as defined in vice\diskimage.h:57
DiskImageDeviceReal = 1
// DiskImageDeviceRaw as defined in vice\diskimage.h:58
DiskImageDeviceRaw = 2
// DiskImageTypeX64 as defined in vice\diskimage.h:60
DiskImageTypeX64 = 0
// DiskImageTypeG64 as defined in vice\diskimage.h:61
DiskImageTypeG64 = 100
// DiskImageTypeG71 as defined in vice\diskimage.h:62
DiskImageTypeG71 = 101
// DiskImageTypeP64 as defined in vice\diskimage.h:63
DiskImageTypeP64 = 200
// DiskImageTypeD64 as defined in vice\diskimage.h:64
DiskImageTypeD64 = 1541
// DiskImageTypeD67 as defined in vice\diskimage.h:65
DiskImageTypeD67 = 2040
// DiskImageTypeD71 as defined in vice\diskimage.h:66
DiskImageTypeD71 = 1571
// DiskImageTypeD81 as defined in vice\diskimage.h:67
DiskImageTypeD81 = 1581
// DiskImageTypeD80 as defined in vice\diskimage.h:68
DiskImageTypeD80 = 8050
// DiskImageTypeD82 as defined in vice\diskimage.h:69
DiskImageTypeD82 = 8250
// DiskImageTypeTap as defined in vice\diskimage.h:70
DiskImageTypeTap = 1531
// DiskImageTypeD1m as defined in vice\diskimage.h:71
DiskImageTypeD1m = 1000
// DiskImageTypeD2m as defined in vice\diskimage.h:72
DiskImageTypeD2m = 2000
// DiskImageTypeD4m as defined in vice\diskimage.h:73
DiskImageTypeD4m = 4000
// C64RamSize as defined in c64\c64mem.h:36
C64RamSize = 0x10000
// C64KernalRomSize as defined in c64\c64mem.h:39
C64KernalRomSize = 0x2000
// C64BasicRomSize as defined in c64\c64mem.h:40
C64BasicRomSize = 0x2000
// C64ChargenRomSize as defined in c64\c64mem.h:41
C64ChargenRomSize = 0x1000
// C64BasicChecksum as defined in c64\c64mem.h:43
C64BasicChecksum = 15702
// C64KernalChecksumR01 as defined in c64\c64mem.h:45
C64KernalChecksumR01 = 54525
// C64KernalChecksumR02 as defined in c64\c64mem.h:46
C64KernalChecksumR02 = 50955
// C64KernalChecksumR03 as defined in c64\c64mem.h:47
C64KernalChecksumR03 = 50954
// C64KernalChecksumR03swe as defined in c64\c64mem.h:48
C64KernalChecksumR03swe = 50633
// C64KernalChecksumR43 as defined in c64\c64mem.h:49
C64KernalChecksumR43 = 50955
// C64KernalChecksumR64 as defined in c64\c64mem.h:50
C64KernalChecksumR64 = 49680
// C64KernalIdR01 as defined in c64\c64mem.h:53
C64KernalIdR01 = 0xaa
// C64KernalIdR02 as defined in c64\c64mem.h:54
C64KernalIdR02 = 0x00
// C64KernalIdR03 as defined in c64\c64mem.h:55
C64KernalIdR03 = 0x03
// C64KernalIdR03swe as defined in c64\c64mem.h:56
C64KernalIdR03swe = 0x03
// C64KernalIdR43 as defined in c64\c64mem.h:57
C64KernalIdR43 = 0x43
// C64KernalIdR64 as defined in c64\c64mem.h:58
C64KernalIdR64 = 0x64
)

// MonBreakpointType as declared in monitor\mon_breakpoint.h:36
type MonBreakpointType int32

// MonBreakpointType enumeration from monitor\mon_breakpoint.h:36
const (
)

// MonInt as declared in vice\monitor.h:38
type MonInt int32

// MonInt enumeration from vice\monitor.h:38
const (
)

// TMemspace as declared in vice\monitor.h:45
type TMemspace int32

// TMemspace enumeration from vice\monitor.h:45
const (
)

// CpuTypeS as declared in vice\monitor.h:56
type CpuTypeS int32

// CpuTypeS enumeration from vice\monitor.h:56
const (
)

// AsmAddrMode as declared in monitor\asm.h:38
type AsmAddrMode int32

// AsmAddrMode enumeration from monitor\asm.h:38
const (
)

// MaincpuOpcodeWriteCycles as declared in vice\maincpu.h:77
const MaincpuOpcodeWriteCycles []uint32 = 
// TRegId as declared in monitor\montypes.h:50
type TRegId int32

// TRegId enumeration from monitor\montypes.h:50
const (
)

// TMemoryOp as declared in monitor\montypes.h:107
type TMemoryOp int32

// TMemoryOp enumeration from monitor\montypes.h:107
const (
)

// TConditional as declared in monitor\montypes.h:117
type TConditional int32

// TConditional enumeration from monitor\montypes.h:117
const (
)

// TRadixtype as declared in monitor\montypes.h:130
type TRadixtype int32

// TRadixtype enumeration from monitor\montypes.h:130
const (
)

// TAction as declared in monitor\montypes.h:139
type TAction int32

// TAction enumeration from monitor\montypes.h:139
const (
)

