// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 23 Jun 2017 22:04:27 MDT.
// By https://git.io/cgogen. DO NOT EDIT.

/*
Package vice provides Go bindings for VICE
*/
package vice
