// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 23 Jun 2017 22:04:27 MDT.
// By https://git.io/cgogen. DO NOT EDIT.

package vice

/*
#include "monitor.h"
#include "maincpu.h"
#include "mem.h"
#include "video.h"
#include "init.h"
#include "diskimage.h"
#include "debug.h"
#include "monitor/mon_breakpoint.h"
#include "c64/c64mem.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// MonitorCpuType as declared in vice\monitor.h:83
type MonitorCpuType struct {
	AsmAddrModeGetSize *func(mode uint32, p0 uint32, p1 uint32, p2 uint32) uint32
	AsmOpcodeInfoGet   *func(p0 uint32, p1 uint32, p2 uint32) []AsmOpcodeInfoS
	MonAssembleInstr   *func(opcodeName string, operand AsmModeAddrInfo) int32
	MonRegisterGetVal  *func(mem int32, regId int32) uint32
	MonRegisterSetVal  *func(mem int32, regId int32, val uint16)
	MonRegisterPrint   *func(mem int32)
	MonRegisterPrintEx *func(mem int32) string
	MonRegisterListGet *func(mem int32) []MonRegListS
	refc2a36abd        *C.monitor_cpu_type_t
	allocsc2a36abd     interface{}
}

// MonitorInterface as declared in vice\monitor.h:132
type MonitorInterface struct {
	Clk                   []uint32
	CurrentBank           int32
	MemBankList           *func() []string
	MemBankFromName       *func(name string) int32
	MemBankRead           *func(bank int32, addr uint16, context unsafe.Pointer) byte
	MemBankPeek           *func(bank int32, addr uint16, context unsafe.Pointer) byte
	MemBankWrite          *func(bank int32, addr uint16, byte byte, context unsafe.Pointer)
	MemIoregListGet       *func(context unsafe.Pointer) []MemIoregListS
	ToggleWatchpointsFunc *func(value int32, context unsafe.Pointer)
	SetBankBase           *func(context unsafe.Pointer)
	GetLineCycle          *func(line []uint32, cycle []uint32, halfCycle []int32)
	Context               unsafe.Pointer
	ref5ef17d6f           *C.monitor_interface_t
	allocs5ef17d6f        interface{}
}

// MonitorCartridgeCommands as declared in vice\monitor.h:207
type MonitorCartridgeCommands struct {
	CartridgeAttachImage          *func(kind int32, filename string) int32
	CartridgeDetachImage          *func(kind int32)
	CartridgeTriggerFreeze        *func()
	CartridgeTriggerFreezeNmiOnly *func()
	ExportDump                    *func()
	refb6ad82c6                   *C.monitor_cartridge_commands_t
	allocsb6ad82c6                interface{}
}

// MemIoregList as declared in vice\mem.h:92
type MemIoregList struct {
	Name           string
	Start          uint16
	End            uint16
	Next           uint32
	Dump           *func(context unsafe.Pointer, address uint16) int32
	Context        unsafe.Pointer
	ref8ed5165d    *C.mem_ioreg_list_t
	allocs8ed5165d interface{}
}

// VideoChipCap as declared in vice\video.h:134
type VideoChipCap struct {
	DsizeAllowed           uint32
	DsizeDefault           uint32
	DsizeLimitWidth        uint32
	DsizeLimitHeight       uint32
	DscanAllowed           uint32
	HwscaleAllowed         uint32
	Scale2xAllowed         uint32
	DoubleBufferingAllowed uint32
	ExternalPaletteName    string
	ref3e03c83             *C.video_chip_cap_t
	allocs3e03c83          interface{}
}

// VideoRenderColorTables as declared in vice\video.h:159
type VideoRenderColorTables struct {
	Updated          int32
	PhysicalColors   [256]uint32
	Ytableh          [256]int32
	Ytablel          [256]int32
	Cbtable          [256]int32
	CbtableOdd       [256]int32
	Crtable          [256]int32
	CrtableOdd       [256]int32
	Cutable          [256]int32
	CutableOdd       [256]int32
	Cvtable          [256]int32
	CvtableOdd       [256]int32
	YuvUpdated       int32
	YuvTable         [512]uint32
	LineYuv0         [6144]int32
	Prevrgbline      [6144]int16
	Rgbscratchbuffer [8192]byte
	ref8b09ecf5      *C.video_render_color_tables_t
	allocs8b09ecf5   interface{}
}

// VideoResources as declared in vice\video.h:176
type VideoResources struct {
	ColorSaturation   int32
	ColorContrast     int32
	ColorBrightness   int32
	ColorGamma        int32
	ColorTint         int32
	PalScanlineshade  int32
	PalBlur           int32
	PalOddlinesPhase  int32
	PalOddlinesOffset int32
	Audioleak         int32
	refe4c1211        *C.video_resources_t
	allocse4c1211     interface{}
}

// VideoRenderConfig as declared in vice\video.h:205
type VideoRenderConfig struct {
	ChipName                    []byte
	VideoResources              VideoResources
	Cap                         []VideoChipCap
	Rendermode                  int32
	DoubleSizeEnabled           int32
	Scalex                      int32
	Scaley                      int32
	Doublescan                  int32
	Hwscale                     int32
	Scale2x                     int32
	Filter                      int32
	ExternalPalette             int32
	ExternalPaletteName         []byte
	DoubleBuffer                int32
	Readable                    int32
	CbmPalette                  []VideoCbmPaletteS
	ColorTables                 VideoRenderColorTablesS
	FullscreenEnabled           int32
	FullscreenStatusbarEnabled  int32
	FullscreenDevice            []byte
	FullscreenDeviceNum         int32
	FullscreenDoubleSizeEnabled int32
	FullscreenDoubleScanEnabled int32
	FullscreenMode              [4]int32
	ref5b975e14                 *C.video_render_config_t
	allocs5b975e14              interface{}
}

// VideoDrawBufferCallback as declared in vice\video.h:262
type VideoDrawBufferCallback struct {
	DrawBufferAlloc *func(canvas []VideoCanvasS, drawBuffer [][]byte, fbWidth uint32, fbHeight uint32, fbPitch []uint32) int32
	DrawBufferFree  *func(canvas []VideoCanvasS, drawBuffer []byte)
	DrawBufferClear *func(canvas []VideoCanvasS, drawBuffer []byte, value byte, fbWidth uint32, fbHeight uint32, fbPitch uint32)
	refb8dd2b44     *C.video_draw_buffer_callback_t
	allocsb8dd2b44  interface{}
}

// VideoCbmColor as declared in vice\video.h:289
type VideoCbmColor struct {
	Luminance      float32
	Angle          float32
	Direction      int32
	Name           []byte
	ref354e7dce    *C.video_cbm_color_t
	allocs354e7dce interface{}
}

// VideoCbmPalette as declared in vice\video.h:299
type VideoCbmPalette struct {
	NumEntries     uint32
	Entries        []VideoCbmColor
	Saturation     float32
	Phase          float32
	Type           int32
	ref94947f76    *C.video_cbm_palette_t
	allocs94947f76 interface{}
}

// DiskImage as declared in vice\diskimage.h:94
type DiskImage struct {
	ReadOnly       uint32
	Device         uint32
	Type           uint32
	Tracks         uint32
	MaxHalfTracks  uint32
	refb8e680ad    *C.disk_image_t
	allocsb8e680ad interface{}
}

// MonitorToggleFunc type as declared in monitor\montypes.h:157
type MonitorToggleFunc func(value int32)

// VideoCanvasS as declared in vice\video.h:55
type VideoCanvasS C.struct_video_canvas_s
